# Generated by Django 4.1.4 on 2022-12-21 01:39
# Generated by Django 4.1.4 on 2022-12-21 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel
        (
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel
        (
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=500)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.location')),
            ],
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lirstname', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signinemail', models.CharField(max_length=250)),
                ('signinpassword', models.CharField(max_length=250)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.signup')),
            ],
        ),
    ]
