# Generated by Django 4.1.4 on 2022-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='check_in',
            field=models.DateTimeField(default='2022-12-22', verbose_name='Check-in date'),
        ),
        migrations.AddField(
            model_name='location',
            name='check_out',
            field=models.DateField(default='2023-12-22', verbose_name='Check-out date'),
        ),
        migrations.AddField(
            model_name='location',
            name='guest',
            field=models.IntegerField(default=0),
        ),
    ]
