# Generated by Django 4.1.4 on 2022-12-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_city_hotel_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signin',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
