# Generated by Django 4.1.4 on 2022-12-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_location_check_in_location_check_out_location_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
