# Generated by Django 4.1.4 on 2022-12-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='check_in',
            field=models.DateTimeField(verbose_name='Check-in date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='check_out',
            field=models.DateTimeField(verbose_name='Check-out date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='New York', max_length=250),
        ),
    ]
