# Generated by Django 4.1.4 on 2022-12-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_rename_city_location_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='city',
        ),
    ]
